#ifndef KERNEL_SCANCODES_H
#define KERNEL_SCANCODES_H

#include <kernel/Keymap.h>
#include <stdint.h>

constexpr uint8_t MOD_NONE  = 0x00;
constexpr uint8_t MOD_SHIFT = 0x01;
constexpr uint8_t MOD_CTRL  = 0x02;
constexpr uint8_t MOD_ALT   = 0x04;

struct ScancodeEntry {
  Key key;
  uint8_t mod;
};

constexpr unsigned int EXTENDED_TABLE_SIZE = 128;

inline const ScancodeEntry &lookupScancode(uint8_t scancode, bool extended);

namespace {

constinit ScancodeEntry scancodeTable[128] = {
  { Key::Unknown,        MOD_NONE  },
  { Key::Escape,         MOD_NONE  },
  { Key::_1,             MOD_NONE  },
  { Key::_2,             MOD_NONE  },
  { Key::_3,             MOD_NONE  },
  { Key::_4,             MOD_NONE  },
  { Key::_5,             MOD_NONE  },
  { Key::_6,             MOD_NONE  },
  { Key::_7,             MOD_NONE  },
  { Key::_8,             MOD_NONE  },
  { Key::_9,             MOD_NONE  },
  { Key::_0,             MOD_NONE  },
  { Key::Minus,          MOD_NONE  },
  { Key::Equals,         MOD_NONE  },
  { Key::Backspace,      MOD_NONE  },
  { Key::Tab,            MOD_NONE  },
  { Key::Q,              MOD_NONE  },
  { Key::W,              MOD_NONE  },
  { Key::E,              MOD_NONE  },
  { Key::R,              MOD_NONE  },
  { Key::T,              MOD_NONE  },
  { Key::Y,              MOD_NONE  },
  { Key::U,              MOD_NONE  },
  { Key::I,              MOD_NONE  },
  { Key::O,              MOD_NONE  },
  { Key::P,              MOD_NONE  },
  { Key::LBracket,       MOD_NONE  },
  { Key::RBracket,       MOD_NONE  },
  { Key::Enter,          MOD_NONE  },
  { Key::LCtrl,          MOD_CTRL  },
  { Key::A,              MOD_NONE  },
  { Key::S,              MOD_NONE  },
  { Key::D,              MOD_NONE  },
  { Key::F,              MOD_NONE  },
  { Key::G,              MOD_NONE  },
  { Key::H,              MOD_NONE  },
  { Key::J,              MOD_NONE  },
  { Key::K,              MOD_NONE  },
  { Key::L,              MOD_NONE  },
  { Key::Semicolon,      MOD_NONE  },
  { Key::Quote,          MOD_NONE  },
  { Key::Backtick,       MOD_NONE  },
  { Key::LShift,         MOD_SHIFT },
  { Key::Backslash,      MOD_NONE  },
  { Key::Z,              MOD_NONE  },
  { Key::X,              MOD_NONE  },
  { Key::C,              MOD_NONE  },
  { Key::V,              MOD_NONE  },
  { Key::B,              MOD_NONE  },
  { Key::N,              MOD_NONE  },
  { Key::M,              MOD_NONE  },
  { Key::Comma,          MOD_NONE  },
  { Key::Period,         MOD_NONE  },
  { Key::Slash,          MOD_NONE  },
  { Key::RShift,         MOD_SHIFT },
  { Key::KeypadAsterisk, MOD_NONE  },
  { Key::LAlt,           MOD_ALT   },
  { Key::Space,          MOD_NONE  },
  { Key::CapsLock,       MOD_NONE  },
  { Key::F1,             MOD_NONE  },
  { Key::F2,             MOD_NONE  },
  { Key::F3,             MOD_NONE  },
  { Key::F4,             MOD_NONE  },
  { Key::F5,             MOD_NONE  },
  { Key::F6,             MOD_NONE  },
  { Key::F7,             MOD_NONE  },
  { Key::F8,             MOD_NONE  },
  { Key::F9,             MOD_NONE  },
  { Key::F10,            MOD_NONE  },
  { Key::NumLock,        MOD_NONE  },
  { Key::ScrollLock,     MOD_NONE  },
  { Key::Keypad7,        MOD_NONE  },
  { Key::Keypad8,        MOD_NONE  },
  { Key::Keypad9,        MOD_NONE  },
  { Key::KeypadMinus,    MOD_NONE  },
  { Key::Keypad4,        MOD_NONE  },
  { Key::Keypad5,        MOD_NONE  },
  { Key::Keypad6,        MOD_NONE  },
  { Key::KeypadPlus,     MOD_NONE  },
  { Key::Keypad1,        MOD_NONE  },
  { Key::Keypad2,        MOD_NONE  },
  { Key::Keypad3,        MOD_NONE  },
  { Key::Keypad0,        MOD_NONE  },
  { Key::KeypadPeriod,   MOD_NONE  },
  { Key::F11,            MOD_NONE  },
  { Key::F12,            MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
  { Key::Unknown,        MOD_NONE  },
};

constinit ScancodeEntry extendedTable[EXTENDED_TABLE_SIZE] = {
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::RCtrl,   MOD_CTRL },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::RAlt,    MOD_ALT  },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Home,    MOD_NONE },
  { Key::Up,      MOD_NONE },
  { Key::PageUp,  MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Left,    MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Right,   MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::End,     MOD_NONE },
  { Key::Down,    MOD_NONE },
  { Key::PageDown,MOD_NONE },
  { Key::Insert,  MOD_NONE },
  { Key::Delete,  MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::LGui,    MOD_NONE },
  { Key::RGui,    MOD_NONE },
  { Key::Apps,    MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
  { Key::Unknown, MOD_NONE },
};

}

const ScancodeEntry &lookupScancode(uint8_t scancode, bool extended)
{
  if (extended && scancode < EXTENDED_TABLE_SIZE) {
    return extendedTable[scancode];
  }
  return scancodeTable[scancode & 0x7F];
}

#endif // KERNEL_SCANCODES_H
