#ifndef KERNEL_VERSION_H
#define KERNEL_VERSION_H

#define MAJOR_VERSION 0
#define MINOR_VERSION 1
#define BUILD_VERSION 0

#define BUILD_DATE __DATE__
#define BUILD_TIME __TIME__

#endif // KERNEL_VERSION_H
