if (CLANG_TIDY)
  find_program(CLANG_TIDY_EXE NAMES clang-tidy)
  if (CLANG_TIDY_EXE)
    message(STATUS "clang-tidy: ${CLANG_TIDY_EXE}")
    set(_DOORS_CLANG_TIDY_EXE "${CLANG_TIDY_EXE}")
  else()
    message(WARNING "CLANG_TIDY=ON but clang-tidy was not found on PATH")
  endif()
else()
  message(STATUS "clang-tidy: OFF")
endif()

if (CPPCHECK)
  find_program(CPPCHECK_EXE NAMES cppcheck)
  if (CPPCHECK_EXE)
    message(STATUS "cppcheck: ${CPPCHECK_EXE}")
  else()
    message(WARNING "CPPCHECK=ON but cppcheck was not found on PATH")
  endif()
else()
  message(STATUS "cppcheck: OFF")
endif()
