if (CLANG_TIDY)
  find_program(CLANG_TIDY_EXE NAMES clang-tidy)
  if (CLANG_TIDY_EXE)
    message(STATUS "clang-tidy: ${CLANG_TIDY_EXE}")
    set(_DOORS_CLANG_TIDY_EXE "${CLANG_TIDY_EXE}")
  else()
    message(WARNING "CLANG_TIDY=ON but clang-tidy was not found on PATH")
  endif()
else()
  message(STATUS "clang-tidy: OFF")
endif()

if (CPPCHECK)
  find_program(CPPCHECK_EXE NAMES cppcheck)
  if (CPPCHECK_EXE)
    message(STATUS "cppcheck: ${CPPCHECK_EXE}")
  else()
    message(WARNING "CPPCHECK=ON but cppcheck was not found on PATH")
  endif()
else()
  message(STATUS "cppcheck: OFF")
endif()

if (CODE_COVERAGE)
  find_program(LCOV_EXE lcov)
  find_program(GENHTML_EXE genhtml)
  if (NOT LCOV_EXE OR NOT GENHTML_EXE)
    set(_missing "")
    if (NOT LCOV_EXE)
      string(APPEND _missing "  lcov\n")
    endif()
    if (NOT GENHTML_EXE)
      string(APPEND _missing "  genhtml\n")
    endif()
    message(FATAL_ERROR
      "CODE_COVERAGE is ON but the following tools were not found on PATH:\n"
      "${_missing}"
      "Install them:\n"
      "  sudo apt install lcov\n"
    )
  endif()
  message(STATUS "Code coverage: ON (-fprofile-arcs -ftest-coverage)")
else()
  message(STATUS "Code coverage: OFF")
endif()
